# Stolen from @jonotrujillo.

# Make sure we are using the latest Homebrew
update

# System formulae
install zsh
install ack
install coreutils
install git
install hg
install tree
install wget
install rsync
install ssh-copy-id
install ctags
install reattach-to-user-namespace

# Development formulae
install rbenv
install ruby-build
install rbenv-gem-rehash
install rbenv-vars
install rbenv-default-gems
install tmux
install tmate
install go

# Remove outdated versions from the cellar
cleanup
