# Stolen from @jonotrujillo.

# Make sure we are using the latest Homebrew
update

# System formulae
install ack
install coreutils
install git
install tree
install wget
install rsync
install ctags
install reattach-to-user-namespace

# Development formulae
install rbenv
install ruby-build
install rbenv-gem-rehash
install rbenv-readline
install rbenv-vars
install tmux
install tmate

# Remove outdated versions from the cellar
cleanup
