#!/usr/bin/env bash

if [ -e `which brew` ]; then
  echo "Hombrew is already installed."
else
  echo "Installing Hombrew"
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  echo "Done..."
fi
