#!/usr/bin/env bash

LINKABLES=$(find * -name "*.symlink")

for linkable in $LINKABLES; do

  LINKABLE_NAME="${linkable##*/}"
  TARGET_NAME=".${LINKABLE_NAME%.symlink}"
  TARGET="$HOME/$TARGET_NAME"

  remove_links() {
    if [[ -L $1 ]]; then
      echo "Removing $1"
      rm $1
    fi
  }

  remove_links $TARGET
done
