#!/usr/bin/env bash

if command -v curl >/dev/null; then
  echo "Installing vim-plug..."
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if command -v vim >/dev/null; then
  echo "Installing vim plugins..."
  vim +PlugInstall +qall
fi
